//  auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_LOGGED_USER_DETAILS_SUCCESS = 'GET_LOGGED_USER_DETAILS_SUCCESS';
export const GET_LOGGED_USER_DETAILS_FAIL = 'GET_LOGGED_USER_DETAILS_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const LOAD_LEADERBOARD_SUCCESS = 'LOAD_LEADERBOARD_SUCCESS';
export const LOAD_LEADERBOARD_FAIL = 'LOAD_LEADERBOARD_FAIL';

// recipeActions
export const GET_RECIPE_DETAILS_SUCCESS = 'GET_RECIPE_DETAILS_SUCCESS';
export const GET_RECIPE_DETAILS_FAIL = 'GET_RECIPE_DETAILS_FAIL';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';
export const GET_TRENDING_RECIPE_LIST_SUCCESS = 'GET_TRENDING_RECIPE_LIST_SUCCESS';
export const GET_TRENDING_RECIPE_LIST_FAIL = 'GET_TRENDING_RECIPE_LIST_FAIL';
export const GET_FOLLOWED_RECIPE_LIST_SUCCESS = 'GET_FOLLOWED_RECIPE_LIST_SUCCESS';
export const GET_FOLLOWED_RECIPE_LIST_FAIL = 'GET_FOLLOWED_RECIPE_LIST_FAIL';
export const GET_SAVED_RECIPE_LIST_SUCCESS = 'GET_SAVED_RECIPE_LIST_SUCCESS';
export const GET_SAVED_RECIPE_LIST_FAIL = 'GET_SAVED_RECIPE_LIST_FAIL';

// saveRecipeActions
export const SAVE_UNSAVE_ACTION_SUCCESS = 'SAVE_UNSAVE_ACTION_SUCCESS';
export const SAVE_UNSAVE_ACTION_FAIL = 'SAVE_UNSAVE_ACTION_FAIL';

// followerActions
export const FOLLOW_UNFOLLOW_USER_SUCCESS = 'FOLLOW_UNFOLLOW_USER_SUCCESS';
export const FOLLOW_UNFOLLOW_USER_FAIL = 'FOLLOW_UNFOLLOW_USER_FAIL';

// reviewActions
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';
export const REVIEWS_IN_RECIPE_SUCCESS = 'REVIEWS_IN_RECIPE_SUCCESS';
export const REVIEWS_IN_RECIPE_FAIL = 'REVIEWS_IN_RECIPE_FAIL';

// ingredientActions
export const INGREDIENT_CREATE_SUCCESS = 'INGREDIENT_CREATE_SUCCESS';
export const INGREDIENT_CREATE_FAIL = 'INGREDIENT_CREATE_FAIL';
export const INGREDIENT_UPDATE_SUCCESS = 'INGREDIENT_UPDATE_SUCCESS';
export const INGREDIENT_UPDATE_FAIL = 'INGREDIENT_UPDATE_FAIL';
export const INGREDIENT_DELETE_SUCCESS = 'INGREDIENT_DELETE_SUCCESS';
export const INGREDIENT_DELETE_FAIL = 'INGREDIENT_DELETE_FAIL';

// instructionActions
export const INSTRUCTION_CREATE_SUCCESS = 'INSTRUCTION_CREATE_SUCCESS';
export const INSTRUCTION_CREATE_FAIL = 'INSTRUCTION_CREATE_FAIL';
export const INSTRUCTION_UPDATE_SUCCESS = 'INSTRUCTION_UPDATE_SUCCESS';
export const INSTRUCTION_UPDATE_FAIL = 'INSTRUCTION_UPDATE_FAIL';
export const INSTRUCTION_DELETE_SUCCESS = 'INSTRUCTION_DELETE_SUCCESS';
export const INSTRUCTION_DELETE_FAIL = 'INSTRUCTION_DELETE_FAIL';

// test
export const TEST_CASE_AUTH = 'TEST_CASE_AUTH';
export const TEST_CASE_RECIPE = 'TEST_CASE_RECIPE';
