# Generated by Django 3.1.12 on 2021-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to='recipes.Recipe'),
        ),
    ]
