# Generated by Django 3.1.12 on 2021-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210913_2115'),
        ('accounts', '0002_useraccount_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='favorites',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishlist', to='recipes.Recipe'),
        ),
    ]
