# Generated by Django 3.1.12 on 2021-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210913_2115'),
        ('accounts', '0003_auto_20210913_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, default=None, related_name='saved_recipes', to='recipes.Recipe'),
        ),
    ]
