//  auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
export const USER_DELETED_FAIL = 'USER_DELETED_FAIL';
export const USER_UPDATED_SUCCESS = 'USER_UPDATED_SUCCESS';
export const USER_UPDATED_FAIL = 'USER_UPDATED_FAIL';
export const LOAD_USER_LIST_SUCCESS = 'LOAD_USER_LIST_SUCCESS';
export const LOAD_USER_LIST_FAIL = 'LOAD_USER_LIST_FAIL';
export const LOAD_USER_DETAILS_SUCCESS = 'LOAD_USER_DETAILS_SUCCESS';
export const LOAD_USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

// recipeActions
export const LOAD_RECIPE_LIST_SUCCESS = 'LOAD_RECIPE_LIST_SUCCESS';
export const LOAD_RECIPE_LIST_FAIL = 'LOAD_RECIPE_LIST_FAIL';
export const RECIPE_SEARCH_SUCCESS = 'RECIPE_SEARCH_SUCCESS';
export const RECIPE_SEARCH_FAIL = 'RECIPE_SEARCH_FAIL';
export const LOAD_RECIPE_DETAILS_SUCCESS = 'LOAD_RECIPE_DETAILS_SUCCESS';
export const LOAD_RECIPE_DETAILS_FAIL = 'LOAD_RECIPE_DETAILS_FAIL';
export const RECIPE_UPDATED_SUCCESS = 'RECIPE_UPDATED_SUCCESS';
export const RECIPE_UPDATED_FAIL = 'RECIPE_UPDATED_FAIL';
export const RECIPE_CREATED_SUCCESS = 'RECIPE_CREATED_SUCCESS';
export const RECIPE_CREATED_FAIL = 'RECIPE_CREATED_FAIL';
export const RECIPE_DELETED_SUCCESS = 'RECIPE_DELETED_SUCCESS';
export const RECIPE_DELETED_FAIL = 'RECIPE_DELETED_FAIL';

//socket
export const CONNECT_SOCKET = 'CONNECT_SOCKET';

//chats
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_FAIL = 'CHAT_LIST_FAIL';
