# Generated by Django 3.1.12 on 2021-09-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='likes',
            new_name='saves',
        ),
    ]
