# Generated by Django 3.1.12 on 2021-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211118_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
