# Generated by Django 3.1.12 on 2021-09-13 12:17

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDuo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, default=None, related_name='duo_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
