version: '3.8'

services:
    web:
        build: .
        command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
            - .:/api
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - 'DJANGO_SECRET_KEY=0o%+e2tv@q!wiot0i3m*#)&q2w3v8nd74ew64+!ilm6&qq-9o5'
            - 'DJANGO_SECURE_SSL_REDIRECT=True'
            - 'EMAIL_HOST_USER=apikey'
            - 'EMAIL_HOST_PASSWORD=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'
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
    postgres_data:
