name: Django CI

on:
    push:

env:
    registry: my_registry_name
    # Not sure these are actually being passed down to rails, set them as the default in database.yml
    DB_HOST: localhost
    DB_USERNAME: postgres
    DB_PASSWORD: postgres

jobs:
    build:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./api
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8]

    services:
        postgres:
            image: postgres:latest
            env:
                POSTGRES_DB: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_USER: postgres
            ports:
                - 5432:5432
            # Set health checks to wait until postgres has started
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5

            steps:
                - uses: actions/checkout@v2
                - name: Set up Python ${{ matrix.python-version }}
                  uses: actions/setup-python@v2
                  with:
                      python-version: ${{ matrix.python-version }}
                - name: Install Dependencies
                  run: |
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                - name: Run Tests
                  run: |
                      pytest
